require 'ffi-compiler/compile_task'

options = ->(t) do
  t.cflags << '-arch x86_64 -arch i386' if t.platform.mac?
  t.cflags << '-std=c99'
  t.ldflags << '-arch x86_64 -arch i386' if t.platform.mac?
end

FFI::Compiler::CompileTask.new('crc', &options)
FFI::Compiler::CompileTask.new('bsd', &options)