require 'ffi-compiler/compile_task'

options = ->(t) do
  t.cflags << "-arch x86_64 -arch i386" if t.platform.mac?
  t.ldflags << "-arch x86_64 -arch i386" if t.platform.mac?
end

FFI::Compiler::CompileTask.new('checksums', &options)